name: Create and publish Docker image

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: nbe95/ha-sip

jobs:
  create-docker-image:
    name: Build and publish Docker image
    runs-on: ubuntu-latest
    needs: [bump-tag-version]
    steps:
      - uses: actions/checkout@v4
      - name: Get commit short SHA
        id: commit
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./ha-sip/
          file: ./Dockerfile
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:${{ steps.commit.outputs.sha_short }}
            ${{ env.IMAGE_NAME }}:latest
